#! /bin/sh
nitrogen --restore
picom -b --config /home/cake/.config/picom/picom.conf

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4

bspc config border_width         3
bspc config window_gap          25
bspc config bottom_padding	5
bspc config top_padding		25

bspc config normal_border_color '#ffae7c'
bspc config focused_border_color '#eb5634'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

/home/cake/.config/polybar/launch.sh
